### ISSUE TITLE
upload blockchain to mega.nz or bittorrent

### ISSUE THREAD

**Issue by douchebanner** [bitcointop/bitcointop#2]
hi, i dont live in china and i can not download from baidu.

could someone upload the blockchain to mega.nz or bittorrent?

thanks

**Comment by bitcointop** [comment]
https://www.bitcointop.org/files/BTT20180210.torrent

https://www.bitcointop.org/index.html#wallets

**Comment by douchebanner** [comment]
i get a 404 page for the torrent :(

**Comment by bitcointop** [comment]
sorry,  try again , pls

**Comment by douchebanner** [comment]
yup, that worked :)
