### ISSUE TITLE
List of Peers?

### ISSUE THREAD

**Issue by NoWay426** [bitcointop/bitcointop#4]
Only connecting to 1 node. Is there a list of nodes to add?

**Comment by bitcointop** [comment]
47.75.32.84
47.52.104.201
47.52.201.220
180.97.220.158

suggest download 
https://www.bitcointop.org/files/BTT20180210.torrent

**Comment by bitcointop** [comment]
torrent update 10/02/2018
https://www.bitcointop.org/files/BTT20180210.torrent
