### ISSUE TITLE
Replay protection safe against Bitcoin Diamond?

### ISSUE THREAD

**Issue by isle2983** [bitcointop/bitcointop#5]
The code seems to use the same replay protection as for Bitcoin Diamond which sets CURRENT_VERSION and MAX_STANDARD_VERSION to 12 in `src/primitives/transaction.h`.
Does this mean that replay attacks between BCD and BTT are possible?

**Comment by bitcointop** [comment]
Thank you very much!!!  We've just upgraded the source code, thank you very much.
